showrepeated:
	@grep -E '(bíhat|mrzat|sychat|mílat|sýchat|přahat|vářet|stýlat|skladnit|lidnit|bízet|hlížet|běhnout|žebračit|tmívat|stehnout|plynit|hášet|chládat|chechtnout|vláknit|tláčet|tělesnit|sklepit|řečtit|příjemnit|mrazovat|mrákat|moučnit|mítat|mírat|lidštit|lednit|dlábnout|chlupit|chichtnout|bledat)$$' potential-new-pairs.tsv | grep "\+"

handchecked:
	@grep -E '(skladnit|lidnit|bízet|žebračit|vláknit|tmívat|plynit|moučnit|lidštit|tělesnit|sklepit|příjemnit|lednit)$$' potential-new-pairs.tsv | grep "\+" > hand-checked-phantoms-to-be-added-to-2.0
